APIにリクエストする
Kyoya-prog/Yumemi_Intern_Task pull request #2
Opened 2021-08-30 06:25 UTC by Kyoya-prog

# やったこと
[このタスク](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/API.md)の実装

# UI
https://user-images.githubusercontent.com/63186144/131294659-18535754-6df9-4e45-b4b5-df7a351d4900.mov

# 特に見て欲しいポイント
MVPで実装してみたが、責務分けは適切かどうか
DIは適切か
YumemiWeatherのレスポンスをenumでまとめたが、このまとめ方は適切か

2021-08-30 08:18 UTC, ruby109 commented on YumemiInternTask/Resource/Assets.xcassets/cloudy.imageset/Contents.json
> +}
https://github.com/Hyperbolic4183/YumemiWeather/pull/4#discussion_r632191017
pdf画像なので、こちらのコメントに参考して、変更してください

2021-08-30 08:19 UTC, novr requested changes

2021-08-30 08:19 UTC, novr commented on YumemiInternTask/Resource/Assets.xcassets/cloudy.imageset/Contents.json
> +  "info" : {
ベクターデータなので
- [x] Preserve Vector Data
- Scale: Single scale
<img width="1512" alt="スクリーンショット 2021-08-30 17 08 38" src="https://user-images.githubusercontent.com/47618299/131307508-de6ea044-dba3-41bb-8150-33b82518be3f.png">

2021-08-30 08:19 UTC, novr commented on YumemiInternTask/Contract/WeatherContract.swift
> +    func showWeatherImage(image: UIImage, color: UIColor)
[IMO] Weather型で渡すことによって、WeatherViewからUIKit(UIImage、 UIColor)への依存を除外できます

2021-08-30 08:19 UTC, novr commented on YumemiInternTask/Presenter/WeatherPresenter.swift
> +import UIKit
不要です

2021-08-30 08:19 UTC, novr commented on YumemiInternTask/Util/YumemiWeather.swift
> +
[IMO] Utilという区切りは境目がだいたい不明瞭です
Weather+UIImageなどでextensionとしてはいかがでしょうか

また、Weather型はUtilでなくValueObjectではないでしょうか

2021-08-30 08:25 UTC, ruby109 commented on YumemiInternTask/View/WeatherViewController.swift
>          setUpSubViews()
[IMO]
setUpSubviewsの方がいいと思います。
UIKitにもaddSubviewというメソッドがあります

2021-08-30 08:26 UTC, Kyoya-prog commented on YumemiInternTask/Contract/WeatherContract.swift
> +    func showWeatherImage(image: UIImage, color: UIColor)
View層なので、UIKitへの依存があっても問題はないと思うのですが、ここではUIKitの依存を除外した方がいいですか？？
また、Viewは何を表示するかという責務に専念させておくべきだと学習したのですが、ここでweatherを渡すと、view側で

``` swift
    func showWeatherImage(weather:Weather) {
        weatherImageView.image = weather.image
        weatherImageView.tintColor = weather.color
    }
```
weatherからプロパティを取り出す処理が必要になりそうです。なのでここはimageとcolorを渡してView側はそれを愚直に表示するという処理の方がいいと思うのですが、どうでしょう？？

2021-08-30 08:35 UTC, Kyoya-prog commented on YumemiInternTask/Util/YumemiWeather.swift
> +
> Weather+UIImageなどでextensionとしてはいかがでしょうか

UIImageのextensionを作りそこにweatherを組み込むということでしょうか？？

>また、Weather型はUtilでなくValueObjectではないでしょうか

すみません。ここよく理解できなかったです🙇‍♂️

2021-08-30 08:45 UTC, novr commented on YumemiInternTask/Util/YumemiWeather.swift
> +
> UIImageのextensionを作りそこにweatherを組み込むということでしょうか？？

Weatherの拡張としてファイルを別に定義すればよいかと

>> また、Weather型はUtilでなくValueObjectではないでしょうか

> すみません。ここよく理解できなかったです🙇‍♂️

[ValueObjectについて](https://qiita.com/kichion/items/151c6747f2f1a14305cc)
DDDに沿う必要はないですが、MVPでも共通的に取り扱うデータの定義として切り出せるかと

2021-08-30 09:40 UTC, novr commented on YumemiInternTask/Contract/WeatherContract.swift
> +    func showWeatherImage(image: UIImage, color: UIColor)
WeatherViewの実装(WeatherViewController)はView層ですが、ContractはView層ではないです

引数がWeather型に閉じていないと、プロパティが増えた場合にInterfaceが変更になってしまいます
またメソッド名がshowWeatherImageなので、`showWeather(_ weather: Weather)`のようすれば違和感はないかと

2021-08-31 01:21 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/76940)

2021-08-31 01:23 UTC, merged